# Pre-commit hooks configuration
# Run 'pre-commit autoupdate' periodically to update hooks to latest versions
# Run 'pre-commit run --all-files' to run all hooks on all files

repos:
  # isort code formatter
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Black code formatter
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  # Markdown linter
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        args: ["--fix", "--disable", "MD013", "--"]

  # Notebook cleaner
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        files: \.ipynb$

  # Detect secrets erroneously committed to the repository
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  # Basic file cleanliness
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace # Removes trailing whitespace
      - id: end-of-file-fixer # Ensures files end with a newline
      - id: check-yaml # Validates YAML syntax
      - id: check-json # Validates JSON syntax
      - id: debug-statements # Catches forgotten debugging statements
      - id: mixed-line-ending # Normalizes line endings
        args: [--fix=lf] # Normalize line endings to LF

  # Optional hooks (disabled by default)
  # Enable with: pre-commit run --hook-stage manual --all-files
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8 # Lint Python files
        additional_dependencies: [flake8-docstrings]
        args: ["--max-line-length=88", "--extend-ignore=E203"]
        stages: [manual]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit # Security linter for Python code
        exclude: ^tests/
        stages: [manual]

  # Local hooks
  - repo: local
    hooks:
      - id: run-tests
        name: run tests
        entry: make run_tests
        language: system
        pass_filenames: false
        always_run: true
