accelerate_config:
  fsdp_config.fsdp_sharding_strategy:
    - "FULL_SHARD"
  dynamo_config.dynamo_backend:
    - "no"
    - "inductor"
  dynamo_config.dynamo_mode:
    - "default"

cli_args:
  mixed_precision:
    - "bf16"
    - "fp16"
    - "no"
  train_batch_size:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
  num_iterations:
    - 100
