accelerate_config:
  fsdp_config.fsdp_sharding_strategy:
    - "FULL_SHARD"
dynamo_config.dynamo_backend:
  - "no"
dynamo_config.dynamo_mode:
  - "default"

cli_args:
  mixed_precision:
    - "bf16"
  train_batch_size:
    - 1
    - 10
  num_iterations:
    - 100
