defaults:
  - launcher: defaults
  - accelerate_config: fsdp_config
  - train_args: wan2_1-i2v
  - _self_

accelerate_config:
  dynamo_config:
    dynamo_backend: "inductor"

train_args:
  train_batch_size: [1,3]
  num_iterations: 20
  resolution: "768,512"
  num_frames: 129
  logging_dir: outputs/wan2_1_benchmark

# Override Hydra's run dir to be the same as logging dir. Not setting this may result
# in errors or unexpected behavior because Hydra by default a run dir `./<date><time>`.
hydra:
  run:
    dir: ${train_args.logging_dir}
