defaults:
  - defaults
  - _self_

model: mochi-1
model_path: genmo/mochi-1-preview
train_data_path: Wild-Heart/Disney-VideoGeneration-Dataset
train_batch_size: 1
num_iterations: 100
resolution: "960,544"
num_frames: 9
