defaults:
  - defaults
  - _self_

model: stable-diffusion-xl
model_path: stabilityai/stable-diffusion-xl-base-1.0
train_data_path: bghira/pseudo-camera-10k
train_batch_size: 20
num_iterations: 200
resolution: 1024
learning_rate: 1e-4
lr_scheduler: "polynomial"
lr_warmup_steps: 100
